In [1]:
import numpy as np

In [46]:
def getPowerSet(S):
    pS = set([])
    pS.add(frozenset([]))
    A = np.array(list(S))
    print(A)
    n = A.size
    for i in range(2**n):
        b = np.binary_repr(i,width=n)
        print(i)
        print(b)
        idx = np.array(list(b),dtype=int)==1
        print(A[idx])
        pS.add(frozenset(A[idx]))
    return pS

In [48]:
S = set(np.arange(4))
pS = getPowerSet(S)
for i in pS:
    print(i)


[0 1 2 3]
0
0000
[]
1
0001
[3]
2
0010
[2]
3
0011
[2 3]
4
0100
[1]
5
0101
[1 3]
6
0110
[1 2]
7
0111
[1 2 3]
8
1000
[0]
9
1001
[0 3]
10
1010
[0 2]
11
1011
[0 2 3]
12
1100
[0 1]
13
1101
[0 1 3]
14
1110
[0 1 2]
15
1111
[0 1 2 3]
frozenset({2})
frozenset({2, 3})
frozenset({0, 2, 3})
frozenset({1, 2})
frozenset({1, 2, 3})
frozenset({0, 3})
frozenset({0, 1})
frozenset({0, 2})
frozenset({0, 1, 2})
frozenset({3})
frozenset({1})
frozenset({0, 1, 2, 3})
frozenset()
frozenset({0, 1, 3})
frozenset({1, 3})
frozenset({0})
